services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - net-monitor
    volumes:
      - ./initMongo:/docker-entrypoint-initdb.d
      - ./data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

networks:
  net-monitor:
    driver: bridge